services:
  website1:
    image: demo-website:latest
    container_name: Container01
    ports:
      - "8081:80"
    volumes:
       - /root/mydata/website1:/usr/local/apache2/htdocs/:rw
    restart: unless-stopped
    networks:
       - ContNet
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

  website2:
    image: fictional-coffee-roastery01:latest
    container_name: Container02
    ports:
      - "8082:80"
    volumes:
       - /root/mydata/website2:/usr/local/apache2/htdocs/:rw
    restart: unless-stopped
    networks:
       - ContNet
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

  website3:
    image: fictional-coffee-roastery:Pro
    container_name: Container03
    ports:
      - "8083:80"
    volumes:
       - /root/mydata/website3:/usr/local/apache2/htdocs/:rw
    restart: unless-stopped
    networks:
       - ContNet
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

  mongodb:
    image: mongo:7.0
    container_name: MongoDB
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

    ports:
      - "192.168.86.128:27017:27017"
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/mongo_user
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongo_pass
    volumes:
      - mongodb_data:/data/db
    networks:
      - ContNet
    secrets:
      - source: mongo_user
        target: mongo_user
        mode: 0444
      - source: mongo_pass
        target: mongo_pass
        mode: 0444

    healthcheck:
      test: >
        mongosh --quiet
        --username $$(cat /run/secrets/mongo_user)
        --password $$(cat /run/secrets/mongo_pass)
        --authenticationDatabase admin
        --eval "db.adminCommand('ping')"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

volumes:
  mongodb_data:

networks:
  ContNet:
    external: true

secrets:
  mongo_user:
    file: ./secrets/mongo_user.txt
  mongo_pass:
    file: ./secrets/mongo_pass.txt
