services:
  web:
    image: linuxbox
    container_name: linuxbox-app
    ports:
      - "8088:80"        # host:container -> visit http://localhost:8088
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.5"      # max half a CPU core
          memory: "128M"   # max 128 MB RAM
